name: Ihihi

on:
  schedule:
    - cron: '0 7 * * 5'   # Saturday at 07:00 UTC
    - cron: '0 11 * * 5'  # Saturday at 11:00 UTC
    - cron: '0 15 * * 5'  # Saturday at 15:00 UTC
    - cron: '0 7 * * 0'   # Sunday at 07:00 UTC
    - cron: '0 11 * * 0'  # Sunday at 11:00 UTC
    - cron: '0 15 * * 0'  # Sunday at 15:00 UTC
    - cron: '0 17 * * 1'  # Tuesday at 17:00 UTC
    - cron: '0 17 * * 3'  # Thursday at 17:00 UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: Create file and commit
      run: |
        FILE="important_code_here.md"
        LINES=$(( ( RANDOM % 91 ) + 10 ))
        > "$FILE"
        for i in $(seq 1 $LINES); do
          echo "$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)" >> "$FILE"
        done
        git config --global user.name "ArtiFisher"
        git config --global user.email "artemis.fisher@gmail.com"
        git add "$FILE"
        git commit -m "Random text commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/artifisher/funsies.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}